#include "DamselUtil.hpp"

#include "damsel.h"

namespace moab {

damsel_entity_type DamselUtil::mtod_entity_type[] = {
    DAMSEL_ENTITY_TYPE_VERTEX,      //  MBVERTEX
    DAMSEL_ENTITY_TYPE_EDGE,  // MBEDGE
    DAMSEL_ENTITY_TYPE_TRI, // MBTRI
    DAMSEL_ENTITY_TYPE_QUAD, //   MBQUAD
    DAMSEL_ENTITY_TYPE_POLYGON, //   MBPOLYGON
    DAMSEL_ENTITY_TYPE_TET,//  MBTET
    DAMSEL_ENTITY_TYPE_PYRAMID,  //   MBPYRAMID
    DAMSEL_ENTITY_TYPE_PRISM,  //   MBPRISM
    DAMSEL_ENTITY_TYPE_UNDEFINED, // MBKNIFE
    DAMSEL_ENTITY_TYPE_HEX,  //   MBHEX,
    DAMSEL_ENTITY_TYPE_POLYHEDRON, //   MBPOLYHEDRON
    DAMSEL_ENTITY_TYPE_UNDEFINED   //   MBENTITYSET
};

EntityType DamselUtil::dtom_entity_type[] = {
    MBVERTEX,      //  MBVERTEX
    MBEDGE,  // MBEDGE
    MBTRI, // MBTRI
    MBQUAD, //   MBQUAD
    MBPOLYGON, //   MBPOLYGON
    MBTET,//  MBTET
    MBPRISM,  //   MBPRISM
    MBPYRAMID,  //   MBPYRAMID
    MBHEX,  //   MBHEX,
    MBPOLYHEDRON, //   MBPOLYHEDRON
    MBMAXTYPE,   //   MBENTITYSET
    MBMAXTYPE // MBMAXTYPE
};

damsel_data_type DamselUtil::mtod_data_type[] = {
    DAMSEL_DATA_TYPE_BYTES, // MB_TYPE_OPAQUE
    DAMSEL_DATA_TYPE_INTEGER, // MB_TYPE_INTEGER
    DAMSEL_DATA_TYPE_DOUBLE, // MB_TYPE_DOUBLE
    DAMSEL_DATA_TYPE_INVALID, // MB_TYPE_BIT
    DAMSEL_DATA_TYPE_HANDLE // MB_TYPE_HANDLE
};

DataType DamselUtil::dtom_data_type[] = {
    MB_TYPE_OPAQUE, // DAMSEL_DATA_TYPE_INVALID = 0,
    MB_TYPE_OPAQUE,   // DAMSEL_DATA_TYPE_BYTES = 1,
    MB_TYPE_INTEGER,  // DAMSEL_DATA_TYPE_INTEGER = 2,
    MB_TYPE_OPAQUE,  // DAMSEL_DATA_TYPE_INT64 = 3,
    MB_TYPE_OPAQUE,  // DAMSEL_DATA_TYPE_FLOAT = 4,
    MB_TYPE_DOUBLE,  // DAMSEL_DATA_TYPE_DOUBLE = 5,
    MB_TYPE_HANDLE,  // DAMSEL_DATA_TYPE_HANDLE = 6,
    MB_TYPE_OPAQUE,  // DAMSEL_DATA_TYPE_ID_T = 7,
    MB_TYPE_OPAQUE,  // DAMSEL_DATA_TYPE_SHORTINT = 8,
    MB_TYPE_OPAQUE  // DAMSEL_DATA_TYPE_PREDEFINED_WATERMARK = 9;
};

}
